name: hi_sg
description: Singapore Tourism Application built with Wikitude Flutter SDK

version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^4.1.1
  path_provider: ^2.0.1
  wakelock: ^0.5.1
  material_floating_search_bar: ^0.2.6

  augmented_reality_plugin_wikitude:
    path: ./plugin/augmented_reality_plugin_wikitude/
  http: ^0.13.3
  flutter_html: ^2.1.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.2
  cloud_firestore: ^3.1.6
  video_player_360: ^0.1.5
  panorama: ^0.4.1
  fuzzywuzzy: ^0.1.7
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.18
  drag_and_drop_lists: ^0.3.2+2
  date_format: ^2.0.5
  geolocator: ^8.0.5
  basic_utils: ^3.9.0
  flutter_map: ^0.14.0
  flutter_map_marker_popup: ^2.1.2
  cached_network_image: ^3.2.0
  azlistview: ^2.0.0
  photo_view: ^0.13.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/explore/
    - assets/img/login/
    - assets/icons/
    - samples/
    - samples/00_My_Test_Program/
    - samples/00_My_Test_Program/js/
    - samples/00_My_Test_Program/css/
    - samples/00_My_Test_Program/assets/
    - samples/01_AR_navigation/
    - samples/01_AR_navigation/js/
    - samples/01_AR_navigation/css/
    - samples/01_AR_navigation/assets/