name: wikitude_flutter_app
description: A new Flutter project.

version: 9.9.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.5.0
  cupertino_icons: ^1.0.3
  location: ^4.1.1
  path_provider: ^2.0.1
  wakelock: ^0.5.1
  material_floating_search_bar: ^0.2.6

  augmented_reality_plugin_wikitude:
    path: ./plugin/augmented_reality_plugin_wikitude/
  http: ^0.13.3
  flutter_html: ^2.1.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_dynamic_links: ^4.0.4
  random_string: ^2.3.1
  google_sign_in: ^5.2.2
  money_converter: ^2.0.1
  cloud_firestore: ^3.1.6
  uuid: ^3.0.5
  video_player_360: ^0.1.5
  panorama: ^0.4.1
  flutter_google_places: ^0.3.0
  web_scraper: ^0.1.4
  beautiful_soup_dart: ^0.2.0
  fuzzywuzzy: ^0.1.7
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.18
  drag_and_drop_lists: ^0.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter:

  uses-material-design: true
  fonts:
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria-Regular.ttf

  assets:
    - assets/icons/AR.svg
    - assets/img/avatar.png
    - assets/img/AR.png
    - assets/img/placeholder.png
    - assets/img/login/change.jpg
    - assets/img/login/dashboard.png
    - assets/img/login/forget.jpg
    - assets/img/login/login.jpg
    - assets/img/login/profile.png
    - assets/img/login/signup.png
    - assets/icons/google.png
    - samples/
    - samples/00_My_Test_Program/
    - samples/00_My_Test_Program/js/
    - samples/00_My_Test_Program/css/
    - samples/00_My_Test_Program/assets/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/js/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/css/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/assets/
    - samples/10_BrowsingPois_5_NativeDetailScreen/
    - samples/10_BrowsingPois_5_NativeDetailScreen/js/
    - samples/10_BrowsingPois_5_NativeDetailScreen/css/
    - samples/10_BrowsingPois_5_NativeDetailScreen/assets/
    - samples/10_BrowsingPois_4_ReloadingContent/
    - samples/10_BrowsingPois_4_ReloadingContent/js/
    - samples/10_BrowsingPois_4_ReloadingContent/css/
    - samples/10_BrowsingPois_4_ReloadingContent/assets/
    - samples/10_BrowsingPois_3_LimitingRange/
    - samples/10_BrowsingPois_3_LimitingRange/js/
    - samples/10_BrowsingPois_3_LimitingRange/css/
    - samples/10_BrowsingPois_3_LimitingRange/assets/
    - samples/10_BrowsingPois_2_AddingRadar/
    - samples/10_BrowsingPois_2_AddingRadar/js/
    - samples/10_BrowsingPois_2_AddingRadar/css/
    - samples/10_BrowsingPois_2_AddingRadar/assets/
    - samples/10_BrowsingPois_1_PresentingDetails/
    - samples/10_BrowsingPois_1_PresentingDetails/js/
    - samples/10_BrowsingPois_1_PresentingDetails/css/
    - samples/10_BrowsingPois_1_PresentingDetails/assets/
    - samples/09_ObtainPoiData_3_FromWebservice/
    - samples/09_ObtainPoiData_3_FromWebservice/js/
    - samples/09_ObtainPoiData_3_FromWebservice/css/
    - samples/09_ObtainPoiData_3_FromWebservice/assets/
    - samples/09_ObtainPoiData_2_FromLocalResource/
    - samples/09_ObtainPoiData_2_FromLocalResource/js/
    - samples/09_ObtainPoiData_2_FromLocalResource/css/
    - samples/09_ObtainPoiData_2_FromLocalResource/assets/
    - samples/09_ObtainPoiData_1_FromApplicationModel/
    - samples/09_ObtainPoiData_1_FromApplicationModel/js/
    - samples/09_ObtainPoiData_1_FromApplicationModel/css/
    - samples/09_ObtainPoiData_1_FromApplicationModel/assets/
    - samples/08_PointOfInterest_4_SelectingPois/
    - samples/08_PointOfInterest_4_SelectingPois/js/
    - samples/08_PointOfInterest_4_SelectingPois/css/
    - samples/08_PointOfInterest_4_SelectingPois/assets/
    - samples/08_PointOfInterest_3_MultiplePois/
    - samples/08_PointOfInterest_3_MultiplePois/js/
    - samples/08_PointOfInterest_3_MultiplePois/css/
    - samples/08_PointOfInterest_3_MultiplePois/assets/
    - samples/08_PointOfInterest_2_PoiWithLabel/
    - samples/08_PointOfInterest_2_PoiWithLabel/js/
    - samples/08_PointOfInterest_2_PoiWithLabel/css/
    - samples/08_PointOfInterest_2_PoiWithLabel/assets/
    - samples/08_PointOfInterest_1_PoiAtLocation/
    - samples/08_PointOfInterest_1_PoiAtLocation/js/
    - samples/08_PointOfInterest_1_PoiAtLocation/css/
    - samples/08_PointOfInterest_1_PoiAtLocation/assets/
    - samples/07_3dModels_6_3dModelAtGeoLocation/
    - samples/07_3dModels_6_3dModelAtGeoLocation/js/
    - samples/07_3dModels_6_3dModelAtGeoLocation/css/
    - samples/07_3dModels_6_3dModelAtGeoLocation/assets/
    - samples/07_3dModels_5_AnimatedModelParts/
    - samples/07_3dModels_5_AnimatedModelParts/js/
    - samples/07_3dModels_5_AnimatedModelParts/css/
    - samples/07_3dModels_5_AnimatedModelParts/assets/
    - samples/07_3dModels_4_SnapToScreen/
    - samples/07_3dModels_4_SnapToScreen/js/
    - samples/07_3dModels_4_SnapToScreen/css/
    - samples/07_3dModels_4_SnapToScreen/assets/
    - samples/07_3dModels_3_Interactivity/
    - samples/07_3dModels_3_Interactivity/js/
    - samples/07_3dModels_3_Interactivity/css/
    - samples/07_3dModels_3_Interactivity/assets/
    - samples/07_3dModels_2_AppearingAnimation/
    - samples/07_3dModels_2_AppearingAnimation/js/
    - samples/07_3dModels_2_AppearingAnimation/css/
    - samples/07_3dModels_2_AppearingAnimation/assets/
    - samples/07_3dModels_1_3dModelOnTarget/
    - samples/07_3dModels_1_3dModelOnTarget/js/
    - samples/07_3dModels_1_3dModelOnTarget/css/
    - samples/07_3dModels_1_3dModelOnTarget/assets/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/js/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/css/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/assets/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/js/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/css/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/assets/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/js/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/css/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/assets/
    - samples/06_ObjectTracking_1_BasicObjectTracking/
    - samples/06_ObjectTracking_1_BasicObjectTracking/js/
    - samples/06_ObjectTracking_1_BasicObjectTracking/css/
    - samples/06_ObjectTracking_1_BasicObjectTracking/assets/
    - samples/05_InstantTracking_6_LoadInstantTarget/
    - samples/05_InstantTracking_6_LoadInstantTarget/js/
    - samples/05_InstantTracking_6_LoadInstantTarget/css/
    - samples/05_InstantTracking_6_LoadInstantTarget/assets/
    - samples/05_InstantTracking_6_LoadInstantTarget/assets/models/
    - samples/05_InstantTracking_6_LoadInstantTarget/assets/buttons/
    - samples/05_InstantTracking_5_SaveInstantTarget/
    - samples/05_InstantTracking_5_SaveInstantTarget/js/
    - samples/05_InstantTracking_5_SaveInstantTarget/css/
    - samples/05_InstantTracking_5_SaveInstantTarget/assets/
    - samples/05_InstantTracking_5_SaveInstantTarget/assets/models/
    - samples/05_InstantTracking_5_SaveInstantTarget/assets/buttons/
    - samples/05_InstantTracking_4_SceneInteraction/
    - samples/05_InstantTracking_4_SceneInteraction/js/
    - samples/05_InstantTracking_4_SceneInteraction/css/
    - samples/05_InstantTracking_4_SceneInteraction/assets/
    - samples/05_InstantTracking_4_SceneInteraction/assets/models/
    - samples/05_InstantTracking_4_SceneInteraction/assets/buttons/
    - samples/05_InstantTracking_3_Interactivity/
    - samples/05_InstantTracking_3_Interactivity/js/
    - samples/05_InstantTracking_3_Interactivity/css/
    - samples/05_InstantTracking_3_Interactivity/assets/
    - samples/05_InstantTracking_3_Interactivity/assets/models/
    - samples/05_InstantTracking_3_Interactivity/assets/buttons/
    - samples/05_InstantTracking_2_3dModelOnPlane/
    - samples/05_InstantTracking_2_3dModelOnPlane/js/
    - samples/05_InstantTracking_2_3dModelOnPlane/css/
    - samples/05_InstantTracking_2_3dModelOnPlane/assets/
    - samples/05_InstantTracking_2_3dModelOnPlane/assets/models/
    - samples/05_InstantTracking_2_3dModelOnPlane/assets/buttons/
    - samples/05_InstantTracking_1_SimpleInstantTracking/
    - samples/05_InstantTracking_1_SimpleInstantTracking/js/
    - samples/05_InstantTracking_1_SimpleInstantTracking/css/
    - samples/05_InstantTracking_1_SimpleInstantTracking/assets/
    - samples/05_InstantTracking_1_SimpleInstantTracking/assets/buttons/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/js/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/css/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/assets/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/js/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/css/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/assets/
    - samples/04_CloudRecognition_1_SingleImageRecognition/
    - samples/04_CloudRecognition_1_SingleImageRecognition/js/
    - samples/04_CloudRecognition_1_SingleImageRecognition/css/
    - samples/04_CloudRecognition_1_SingleImageRecognition/assets/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/js/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/css/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/assets/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/assets/models/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/js/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/css/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/assets/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/assets/models/
    - samples/03_MultipleTargets_1_MultipleTargets/
    - samples/03_MultipleTargets_1_MultipleTargets/js/
    - samples/03_MultipleTargets_1_MultipleTargets/css/
    - samples/03_MultipleTargets_1_MultipleTargets/assets/
    - samples/03_MultipleTargets_1_MultipleTargets/assets/models/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/js/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/css/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/assets/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/js/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/css/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/assets/
    - samples/02_AdvancedImageTracking_1_Gestures/
    - samples/02_AdvancedImageTracking_1_Gestures/js/
    - samples/02_AdvancedImageTracking_1_Gestures/css/
    - samples/02_AdvancedImageTracking_1_Gestures/assets/
    - samples/01_ImageTracking_5_Bonus-Sparkles/
    - samples/01_ImageTracking_5_Bonus-Sparkles/js/
    - samples/01_ImageTracking_5_Bonus-Sparkles/css/
    - samples/01_ImageTracking_5_Bonus-Sparkles/assets/
    - samples/01_ImageTracking_4_HtmlDrawable/
    - samples/01_ImageTracking_4_HtmlDrawable/js/
    - samples/01_ImageTracking_4_HtmlDrawable/css/
    - samples/01_ImageTracking_4_HtmlDrawable/assets/
    - samples/01_ImageTracking_3_Interactivity/
    - samples/01_ImageTracking_3_Interactivity/js/
    - samples/01_ImageTracking_3_Interactivity/css/
    - samples/01_ImageTracking_3_Interactivity/assets/
    - samples/01_ImageTracking_2_DifferentTargets/
    - samples/01_ImageTracking_2_DifferentTargets/js/
    - samples/01_ImageTracking_2_DifferentTargets/css/
    - samples/01_ImageTracking_2_DifferentTargets/assets/
    - samples/01_ImageTracking_1_ImageOnTarget/
    - samples/01_ImageTracking_1_ImageOnTarget/js/
    - samples/01_ImageTracking_1_ImageOnTarget/css/
    - samples/01_ImageTracking_1_ImageOnTarget/assets/
